# Picking parameters

# the name of the arm kinematic chain group given when moveit was configured
arm_group_name: arm

# how accurate you want a cartesian pose to be achieved
# if set too low IK is likely to fail, if set too high arm will not reach accurately
arm_goal_tolerance: 0.01   # default: 0.01

# how many attempts moveit will make to compute a graping plan
pick_attempts: 10   # default: 10
