# Picking parameters

# the name of the arm kinematic chain group given when moveit was configured
arm_group_name: arm

# the name of the moveit gripper group
hand_group_name: hand

# how accurate you want a cartesian pose to be achieved
# if set too low IK is likely to fail, if set too high arm will not reach accurately
arm_goal_tolerance: 0.01   # default: 0.01

# how many attempts moveit will make to compute a graping plan
pick_attempts: 10          # default: 10

# timeout for the pick - planning
planning_time: 10.0        # default: 5.0

# if true, before picking the arm will go to a predefined posture (pregrasp_posture)
pregrasp_posture_required: False # default: True

# the predefined arm posture to go before picking an object
pregrasp_posture: 'home'
