# Pose generator params

# sampling params

# step: defined in radians, this is the sampling resolution
# in other words a sample will be created with increments of this size
roll_step:     0.6283184
pitch_step:    0.3
yaw_step:      0.3

# the angular range in radians to begin, stop sampling
roll_start:    0.0
roll_end:      5.654866 # pi x 2.0 - roll step / 2.0
pitch_start:  -0.3
pitch_end:     0.3
yaw_start:    -0.3
yaw_end:       0.3
