# this parameters are specific to mia hand on ur5 robot
# the gripper orientation when grasping from the side in quaternion
grasp_orientations:
    side_grasp: [-0.190164, 0.714782, -0.133767, -0.659568] # orientation in quaternion
    top_grasp:  [0.995892, -0.006266, -0.016992, -0.088719] # orientation in quaternion

# offest is w.r.t. example prerecorded orientation ref frame, NOT w.r.t object!
object_offset_params:
  cylinder:
    side_grasp: [0.0, 0.0, 0.0]
    top_grasp: [0.0, 0.0, -0.08]
  insole:
    side_grasp: [0.0, 0.0, 0.0]
    top_grasp: [0.0, 0.0, 0.0]
  tall_insole:
    side_grasp: [0.0, 0.0, 0.0]
    top_grasp: [0.0, 0.0, 0.0]

# Pose generator (sampling) params
spherical_sampling:
  side_grasp:
    roll_step:     0.6283184
    pitch_step:    0.3
    yaw_step:      0.3
    roll_start:    0.0
    roll_end:      5.654866 # pi x 2.0 - roll step / 2.0
    pitch_start:  -0.3
    pitch_end:     0.3
    yaw_start:    -0.3
    yaw_end:       0.3
  top_grasp:
    roll_step:     0.3
    pitch_step:    0.3
    yaw_step:      0.6283184
    roll_start:   -0.3
    roll_end:      0.3
    pitch_start:  -0.3
    pitch_end:     0.3
    yaw_start:     0.0
    yaw_end:       5.654866 # pi x 2.0 - roll step / 2.0
